### PR TITLE
new content type: geojson

### PR DESCRIPTION
**Pull request by dmpe**
#3

### CODE REVIEW

**Comment by yihui** [comment]
mimemap.R is automatically generated, so it will be overwritten next time unless Debian/Ubuntu supports this content type. To add new types, please do it in `mimeextra`: https://github.com/yihui/mime/blob/master/R/mime.R#L58

**Comment by dmpe** [comment]
Thanks, I saw that the generated file now, after I have already pushed that commit. Should not work in the evening. :)
Now corrected.

**Comment by yihui** [comment]
Can you only do the one thing you described (i.e. add geojson) and leave mimemap.R alone? One-liner PR's are much easier for me to merge (sometimes I just do it on my phone while I'm still in bed). I don't mean you should not make other changes, but let's finish one thing a time. The more changes you introduce in a single PR, the more cognitive overhead there will be (although in this particular case it looks trivial, it is not really trivial because I'll have to think what I should do after my Ubuntu box generates different output than yours).

Now I'll need to you to squash your commits into one: https://github.com/yihui/knitr/blob/master/CONTRIBUTING.md#pull-requests Thanks!

**Comment by dmpe** [comment]
Thanks  Yuhui !

**Comment by yihui** [comment]
Well, I'm unable to merge because you bumped the version number inappropriately (I don't know how you managed to bump it from 0.3 instead of 0.3.1). Can you let me bump the version number myself? (Again, absolutely minimal changes in PR if possible)

**Comment by dmpe** [comment]
Sorry! This was most probably to due to squashing commits & rebasing inappropriately. See #5

**Pull request closed without merging**
